name: sample-workflow
on: [push]
jobs:     
  explore-first-github-workflow:
    runs-on: ubuntu-latest
    steps:
      - run: echo  "The job automatically triggered by a ${{ github.event_name }} event"
      - run: echo  "The job is now running on ${{ runner.os }} server hosted by GitHub"
      - run: echo  "The name of your branch is ${{ github.ref }} and your repository is ${{ github.re pository }}"
      - name: Check out repository code
      - uses: actions/checkout@2
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner"
      - run: echo "The workflow is now ready to test your code on the runner"
      - run: echo "This job's status if ${{ job.status }}"
