name: sample-workflow
on: [push]
jobs:
  explore-first-github-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Print event information
        run: echo "The job was automatically triggered by a ${{ github.event_name }} event"
      
      - name: Print runner information
        run: echo "The job is now running on a ${{ runner.os }} server hosted by GitHub"
      
      - name: Print branch and repository information
        run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}"
      
      - name: Check out repository code
        uses: actions/checkout@v2
      
      - name: Confirm repository cloning
        run: echo "The ${{ github.repository }} repository has been cloned to the runner"
      
      - name: Ready to test code
        run: echo "The workflow is now ready to test your code on the runner"
      
      - name: Print job status
        run: echo "This job's status is ${{ job.status }}"
      
      - name: List all files in the repository
        run: |
          echo "Listing all files in the repository:"
          ls -R ${{ github.workspace }}
